FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json /app/
RUN npm ci

COPY . /app

ARG NEXT_PUBLIC_SEASON_API_BASE_URL=http://localhost:8001
ENV NEXT_PUBLIC_SEASON_API_BASE_URL=${NEXT_PUBLIC_SEASON_API_BASE_URL}

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
