"use client";

import { useEffect, useState } from "react";

// Module-level cache so SVGs are fetched only once per session even
// if the same card is mounted multiple times (flip, re-render, etc.)
const _cache = new Map<string, string>();

interface InlineSvgCardProps {
  url: string | null | undefined;
  className?: string;
  style?: React.CSSProperties;
  alt?: string;
}

/**
 * Renders a card SVG inline in the DOM instead of via <img>.
 *
 * When SVG is embedded as <img>, mobile browsers rasterize the entire SVG
 * at CSS pixel resolution (1x) whenever a filter is present, causing blurry
 * text and mis-scaled element positions on high-DPR screens.
 *
 * Inline SVG is rendered as a live vector document at the device's full DPR,
 * so all text stays sharp and positions stay exact.
 *
 * While the SVG is being fetched we show the original <img> as a placeholder
 * so there is no layout shift.
 */
export function InlineSvgCard({ url, className, style, alt }: InlineSvgCardProps) {
  const [svg, setSvg] = useState<string | null>(() => (url ? (_cache.get(url) ?? null) : null));

  useEffect(() => {
    if (!url) return;
    if (_cache.has(url)) {
      setSvg(_cache.get(url)!);
      return;
    }

    const controller = new AbortController();

    fetch(`/api/svg-proxy?url=${encodeURIComponent(url)}`, {
      signal: controller.signal,
    })
      .then((r) => {
        if (!r.ok) throw new Error(`proxy ${r.status}`);
        return r.text();
      })
      .then((text) => {
        // Strip XML declaration; leave SVG root width/height intact —
        // CSS overrides them so the SVG fills the container.
        const clean = text.replace(/<\?xml[^>]*\?>\s*/g, "");
        _cache.set(url, clean);
        setSvg(clean);
      })
      .catch((err) => {
        if (err.name !== "AbortError") {
          // Keep the <img> fallback; nothing to do
        }
      });

    return () => controller.abort();
  }, [url]);

  if (!svg) {
    if (!url) return null;
    // eslint-disable-next-line @next/next/no-img-element
    return <img className={className} src={url} alt={alt ?? ""} style={style} />;
  }

  return (
    <div
      className={`${className ?? ""} inline-svg-card`}
      style={style}
      // SVG content is generated by our own Python backend — not user input
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
