"use client";

import { useEffect, useId, useRef, useState } from "react";

// Fetched SVG texts are cached before ID-scoping so the raw text can be
// re-scoped with different per-instance prefixes.
const _fetchCache = new Map<string, string>();

/**
 * Prefix every id="X", url(#X), href="#X" and xlink:href="#X" occurrence in
 * the SVG text with a unique string so that multiple inline SVGs on the same
 * page never share IDs (which would make filters / gradients bleed across cards).
 */
function scopeIds(svgText: string, prefix: string): string {
  // Collect all IDs declared in this SVG
  const ids: string[] = [];
  svgText.replace(/\bid="([^"]+)"/g, (_, id: string) => {
    ids.push(id);
    return _;
  });

  let out = svgText;
  for (const id of ids) {
    const newId = `${prefix}${id}`;
    // Simple string split/join avoids regex special-character escaping issues
    out = out.split(`id="${id}"`).join(`id="${newId}"`);
    out = out.split(`url(#${id})`).join(`url(#${newId})`);
    out = out.split(`href="#${id}"`).join(`href="#${newId}"`);
    out = out.split(`xlink:href="#${id}"`).join(`xlink:href="#${newId}"`);
  }
  return out;
}

interface InlineSvgCardProps {
  url: string | null | undefined;
  className?: string;
  style?: React.CSSProperties;
  alt?: string;
}

/**
 * Renders a card SVG inline in the DOM instead of via <img>.
 *
 * When SVG is embedded as <img>, mobile browsers rasterize the entire SVG
 * at CSS pixel resolution (1x) whenever a filter is present, causing blurry
 * text and mis-scaled element positions on high-DPR screens.
 *
 * Inline SVG is rendered as a live vector document at the device's full DPR,
 * so all text stays sharp and positions stay exact.
 *
 * While the SVG is being fetched we show the original <img> as a placeholder
 * so there is no layout shift.
 */
export function InlineSvgCard({ url, className, style, alt }: InlineSvgCardProps) {
  // Stable unique prefix for this component instance — prevents ID collisions
  // when multiple cards are rendered inline on the same page.
  const reactId = useId();
  // useId returns ":r0:" style strings — strip non-alphanumeric for SVG IDs
  const prefix = useRef(`svg${reactId.replace(/[^a-z0-9]/gi, "")}_`).current;

  const [svg, setSvg] = useState<string | null>(null);

  useEffect(() => {
    if (!url) return;

    // If already in cache, scope and set immediately
    if (_fetchCache.has(url)) {
      setSvg(scopeIds(_fetchCache.get(url)!, prefix));
      return;
    }

    const controller = new AbortController();

    fetch(`/api/svg-proxy?url=${encodeURIComponent(url)}`, {
      signal: controller.signal,
    })
      .then((r) => {
        if (!r.ok) throw new Error(`proxy ${r.status}`);
        return r.text();
      })
      .then((text) => {
        // Strip XML declaration before caching
        const raw = text.replace(/<\?xml[^>]*\?>\s*/g, "");
        _fetchCache.set(url, raw);
        setSvg(scopeIds(raw, prefix));
      })
      .catch((err) => {
        if (err.name !== "AbortError") {
          // Fetch failed — the <img> fallback remains visible
        }
      });

    return () => controller.abort();
  }, [url, prefix]);

  if (!svg) {
    if (!url) return null;
    // eslint-disable-next-line @next/next/no-img-element
    return <img className={className} src={url} alt={alt ?? ""} style={style} />;
  }

  return (
    <div
      className={`${className ?? ""} inline-svg-card`}
      style={style}
      // SVG content is generated by our own Python backend — not user input
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
